version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: '18'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn

build_script:
  - yarn
  - yarn build

artifacts:
  - path: dist
    name: TrelloClone
